In [2]:
## SPD server list find

In [1]:
import os
import pandas as pd

In [7]:
!chdir Desktop

In [8]:
os.getcwd()

'C:\\Users\\dkaithav'

In [9]:
!cd Desktop

In [11]:
os.chdir('.\\Desktop\\')

In [12]:
os.getcwd()

'C:\\Users\\dkaithav\\Desktop'

In [13]:
os.listdir()

['Acronymns.xlsx', 'desktop.ini', 'SPD_Express_Global - Domain_20200406.xlsx']

In [30]:
filter_files

['ACA Server List',
 'AHS (AS400 H&G) Server List',
 'AXIS Server List',
 'CDU Server List',
 'CIA Server List',
 'Courier Debrief Server List',
 'DCC Server List',
 'DCE Server List',
 'DPA_DPSS Server List',
 'EDD (GDDS) Server List',
 'ePOD Server List',
 'Express Clearance Server List',
 'FCM Server List',
 'GCA Server List',
 'GDA Server List',
 'GOP Server List',
 'GTS Server List',
 'HIC Server List',
 'IAS_ODB Server List',
 'MCC Server List',
 'MS Server List',
 'OCNT Server List',
 'ODD Server List',
 'PAS Server List',
 'RAR Server List',
 'SATS AM Server List',
 'SATS APEC Server List',
 'SATS CN Server List',
 'SATS EU Server List',
 'SCL Server List',
 'SHP Server List',
 'TAS Server List',
 'UMEX Server List',
 'WAS Server List',
 'WCC Server List',
 'ADM Server List',
 'AQCC Server List',
 'CCS_CQS Server List',
 'DCT Server List',
 'DCVS3 Server List',
 'DIMS Server List',
 'EDMS Server List',
 'GCDB Server List',
 'GENESIS Server List',
 'GLS Server List',
 'GREF Server List',
 'GSS Server List',
 'ISDX Server List',
 'QSMS Server List',
 'TTS Server List',
 'MyDHL+ Server List',
 'Allogis Server List',
 'CSLite Server List',
 'CSV Server List',
 'DCI EU Server List',
 'DCS EU Server List',
 'DHL.com Server List',
 'DHL Express Mobile Server List',
 'Easyship Server List',
 'EIP_ECOM GATEWAY Server List',
 'ELP Server List',
 'Emailship Server List',
 'ESECURE Server List',
 'GCCU Suite Server List',
 'GEMA Server List',
 'GSPL Server List',
 'IntraShip Server List',
 'MCT Server List',
 'MRT Server List',
 'My DHL API Server List',
 'MyDHL Portal Server List',
 'NPTS Server List',
 'PROVIEW Server List',
 'PROXIMATE Server List',
 'XML-PI Server List',
 'CRISP Server List',
 'DVRA Server List',
 'DVRA OLS Server List',
 'EzyBill Server List',
 'FDS Server List',
 'GRE Server List',
 'GWEB+ Server List',
 'GWS Server List',
 'IBS Server List',
 'IBS+ Server List',
 'MyBill Server List',
 'SAP Server List',
 'SUN54 Server List',
 'CI (AM, AP) Server List',
 'CI _ CMP (EU) Server List',
 'DCG (NZD) Server List',
 'DMG Server List',
 'ESP (ESB) Server List',
 'GIA Server List',
 'PRIME Server List',
 'C360 Server List',
 'Comet Server List',
 'COMET APP Server List',
 'CS Combine Server List',
 'DDW.c Server List',
 'Discover.dhl.com Server List',
 'GCPT Server List',
 'GSI Server List',
 'G-SMART Server List',
 'GSRT Server List',
 'iDW Server List',
 'INSIGHT Server List',
 'ISL Server List',
 'LRT Server List',
 'NPA Server List',
 'OneView Server List',
 'OPMc Server List',
 'OPMS Server List',
 'PAPAYA Server List',
 'RCG Server List',
 'RFSP Server List',
 'Sherloc Server List',
 'SPT Server List',
 'START Server List',
 'TM1 Server List']

In [58]:
xls = pd.ExcelFile('SPD_Express_Global - Domain_20200406.xlsx')
filter_files = [col for col in xls.sheet_names if 'Server List' in col]
i=0
list_df = []
for file in filter_files:
    df = pd.read_excel(io='SPD_Express_Global - Domain_20200406.xlsx', sheet_name=file, skiprows=8)
    list_df.append(df)

In [59]:
all =pd.concat(list_df, axis=0)
all.to_csv('allservers.csv', index=False)
all

,Unnamed: 0,Service Names,Server Name,Status,Description,HW,OS,DB,MW,CPUs,Cors,RAM,Unnamed: 12
0,NaN,"ACA EU CBJ SUPPORT, ACA IAS CBJ PROD",HNGAPP4,In Production,Project name IAS ACA EOSL Tech Refresh Project...,HP ProLiant BL460c G7,Red Hat Enterprise Linux 6 64b,NaN,IBM MQ 8.0,2,12,48,NaN
1,NaN,"ACA EU CBJ SUPPORT, ACA IAS CBJ PROD",HNGAPP4,In Production,Project name IAS ACA EOSL Tech Refresh Project...,HP ProLiant BL460c G7,Red Hat Enterprise Linux 6 64b,NaN,IBM MQ 8.0,2,12,48,NaN
2,NaN,"ACA EU CBJ SUPPORT, ACA IAS CBJ PROD",HNGAPP5,In Production,Server usage: IAS ACA app backup server,HP ProLiant BL460c G7,Red Hat Enterprise Linux 6 64b,NaN,IBM MQ 8.0,2,12,48,NaN
3,NaN,"ACA EU CBJ SUPPORT, ACA IAS CBJ PROD",HNGAPP5,In Production,Server usage: IAS ACA app backup server,HP ProLiant BL460c G7,Red Hat Enterprise Linux 6 64b,NaN,IBM MQ 8.0,2,12,48,NaN
4,NaN,ACA IAS CBJ PROD,HNGAPP2,In Production,Project name IAS ACA EOSL Tech Refresh Project...,HP ProLiant BL460c G7,Red Hat Enterprise Linux 6 64b,NaN,IBM MQ 8.0,2,12,48,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
17,NaN,GLOBAL EXPRESS TM1,MYKULWSPC000219,In Production,Cloud PRODUCTION server MYKULWSPC000219,VMware Virtual Machine,MICROSOFT Windows Server 2016 Standard Edition...,NaN,NaN,-,-,-,NaN
18,NaN,GLOBAL EXPRESS TM1,MYKULWSTC000059,In Test,Cloud TEST server MYKULWSTC000059,VMware Virtual Machine,MICROSOFT Windows Server 2016 Standard Edition...,NaN,NaN,-,-,-,NaN
19,NaN,GLOBAL EXPRESS TM1,MYKULWSTC000066,In Test,Cloud TEST server MYKULWSTC000066,VMware Virtual Machine,MICROSOFT Windows Server 2016 Standard Edition...,NaN,NaN,-,-,-,NaN
20,NaN,GLOBAL EXPRESS TM1,MYKULWSTC000142,In Test,Cloud TEST server MYKULWSTC000142,VMware Virtual Machine,MICROSOFT Windows Server 2012 R2 Standard Edition,MICROSOFT SQL rver 2016,NaN,-,-,-,NaN
21,NaN,GLOBAL EXPRESS TM1,MYKULWSTC000220,In Test,Cloud TEST server MYKULWSTC000220,VMware Virtual Machine,MICROSOFT Windows Server 2016 Standard Edition...,NaN,NaN,-,-,-,NaN

In [53]:
os.listdir()

['Acronymns.xlsx',
 'allservers.csv',
 'desktop.ini',
 'SPD_Express_Global - Domain_20200406.xlsx']

In [46]:
df1 = pd.read_excel(io='SPD_Express_Global - Domain_20200406.xlsx', sheet_name='AXIS Server List', skiprows=8)

In [47]:
df2 = pd.read_excel(io='SPD_Express_Global - Domain_20200406.xlsx', sheet_name='GCDB Server List', skiprows=8)

,Unnamed: 0,Service Names,Server Name,Status,Description,HW,OS,DB,MW,CPUs,Cors,RAM,Unnamed: 12
0,NaN,GCDB CBJ PROD,MYKULLS1733,In Production,"GCDB CBJ PROD, GCDB Portal Production",VMware Virtual Machine,Red Hat Enterprise Linux 7 64b,NaN,NaN,6,6,24,NaN
1,NaN,GCDB CBJ PROD,MYKULLS1734,In Production,"GCDB CBJ PROD, GCDB Portal Production",VMware Virtual Machine,Red Hat Enterprise Linux 7 64b,NaN,NaN,6,6,24,NaN
2,NaN,GCDB CBJ PROD,MYKULLS1735,In Production,"GCDB CBJ PROD, GCDB Web Services Production",VMware Virtual Machine,Red Hat Enterprise Linux 7 64b,NaN,Oracle WebLogic Application Server 12c (12.2.x),12,12,64,NaN
3,NaN,GCDB CBJ PROD,MYKULLS1736,In Production,"GCDB CBJ PROD, GCDB Web Services Production",VMware Virtual Machine,Red Hat Enterprise Linux 7 64b,NaN,Oracle WebLogic Application Server 12c (12.2.x),12,12,64,NaN
4,NaN,GCDB CBJ PROD,MYKULLS1737,In Production,"GCDB CBJ PROD, GCDB DQE Production",VMware Virtual Machine,Red Hat Enterprise Linux 7 64b,NaN,NaN,6,6,24,NaN

In [48]:
pd.concat([df1, df2])

,Unnamed: 0,Service Names,Server Name,Status,Description,HW,OS,DB,MW,CPUs,Cors,RAM,Unnamed: 12
0,NaN,AXIS AIMS PROD,MYTPMLS1151,In Production,"AXIS AIMS PROD, Database cluster, node 1",HP ProLiant DL360 Gen10,Red Hat Enterprise Linux 7 64b,Oracle Database 12.2.0.1.0 EE,NaN,1,8,64,NaN
1,NaN,AXIS AIMS PROD,MYTPMLS1152,In Production,"AXIS AIMS PROD, Database cluster, node 2",HP ProLiant DL360 Gen10,Red Hat Enterprise Linux 7 64b,Oracle Database 12.2.0.1.0 EE,NaN,1,8,64,NaN
2,NaN,AXIS CBJ PROD,MYKULLS1969,In Production,"AXIS CBJ PROD, Database cluster, node 1",HP ProLiant DL360 Gen10,Red Hat Enterprise Linux 7 64b,Oracle Database 12.2.0.1.0 EE,NaN,1,8,64,NaN
3,NaN,AXIS CBJ PROD,MYKULLS1970,In Production,"AXIS CBJ PROD, Database cluster, node 2",HP ProLiant DL360 Gen10,Red Hat Enterprise Linux 7 64b,Oracle Database 12.2.0.1.0 EE,NaN,1,8,64,NaN
4,NaN,AXIS PRG PROD,CZCHOLS4189,In Production,"AXIS PRG PROD, Database cluster, node 1",HP ProLiant DL360 Gen10,Red Hat Enterprise Linux 7 64b,Oracle Database 12.2.0.1.0 EE,NaN,1,8,64,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
27,NaN,GCDB PRG PROD,CZCHOLS4306,In Production,"GCDB PRG PROD, GCDB MongoDB Server 02 PROD",VMware Virtual Machine,Red Hat Enterprise Linux 7 64b,MongoDB 3.4,NaN,12,12,48,NaN
28,NaN,GCDB PRG PROD,CZCHOLS4307,In Production,"GCDB PRG PROD, GCDB NodeJS Web Services 02 PROD",VMware Virtual Machine,Red Hat Enterprise Linux 7 64b,NaN,NaN,24,24,96,NaN
29,NaN,GCDB PRG PROD,CZCHOLS4308,In Production,"GCDB PRG PROD, GCDB InformixDB 03 PROD",VMware Virtual Machine,Red Hat Enterprise Linux 7 64b,IBM Informix 12.10,NaN,4,4,16,NaN
30,NaN,GCDB RU,RUMOWLSX028,In Production,NetBackup server,HP ProLiant DL360 Gen8,Red Hat Enterprise Linux 6 64b,NaN,NaN,-,-,-,NaN
31,NaN,GCDB CBJ PROD,MYKULLSPC000207,In Production,Cloud PRODUCTION server MYKULLSPC000207,VMware Virtual Machine,Red Hat Enterprise Linux 7 64b,IBM Informix 12.10,NaN,-,-,-,NaN